version: "3.7"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_server
    environment:
      SA_PASSWORD: '${DB_PASSWORD}'
      ACCEPT_EULA: '${ACCEPT_EULA}'
    ports:
      - '1433:1433'
    expose:
      - 1433
    volumes:
      - 'volatilemssql:/var/lib/mssql/data'
    networks:
      - volatile
    restart: always
  serempre_api:
    build: .
    container_name: serempre_api
    environment:
      NODE_ENV: development
    ports:
      - 5023:5023
    env_file:
      - .env
    links:
      - mssql
    depends_on:
      - mssql
    volumes:
      - '.:/app'
      - '/app/node_modules'
    networks:
      - volatile
    restart: always
    command: npm run start:prod
networks:
  volatile:
    driver: bridge
volumes:
  volatilemssql:
    driver: local
